package io.github.eckig.libavoid;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

public class TestCppPortpenaltyRerouting01
{
    @Test
    public void testpenaltyRerouting01()
    {
    Router router = new Router(Router.RouterFlag.OrthogonalRouting);
    router.setRoutingParameter(Router.RoutingParameter.segmentPenalty, 10);
    router.setRoutingParameter(Router.RoutingParameter.anglePenalty, 0);
    router.setRoutingParameter(Router.RoutingParameter.crossingPenalty, 1e+09);
    router.setRoutingParameter(Router.RoutingParameter.fixedSharedPathPenalty, 0);
    router.setRoutingParameter(Router.RoutingParameter.portDirectionPenalty, 0);
    router.setRoutingParameter(Router.RoutingParameter.shapeBufferDistance, 0);
    router.setRoutingParameter(Router.RoutingParameter.idealNudgingDistance, 4);
    router.setRoutingParameter(Router.RoutingParameter.reverseDirectionPenalty, 0);
    router.setRoutingOption(Router.RoutingOption.nudgeOrthogonalSegmentsConnectedToShapes, false);
    router.setRoutingOption(Router.RoutingOption.penaliseOrthogonalSharedPathsAtConnEnds, false);
    router.setRoutingOption(Router.RoutingOption.nudgeOrthogonalTouchingColinearSegments, false);
    router.setRoutingOption(Router.RoutingOption.performUnifyingNudgingPreprocessingStep, true);
    router.setRoutingOption(Router.RoutingOption.nudgeSharedPathsWithCommonEndPoint, true);
    Polygon polygon = new Polygon();
    ConnRef connRef = null;
    ConnEnd srcPt = new ConnEnd();
    ConnEnd dstPt = new ConnEnd();
    ConnEnd heConnPt = new ConnEnd();
    Polygon newRoute = new Polygon();
    polygon = new Polygon(4);
    polygon.setPoint(0, new Point(449, 491));
    polygon.setPoint(1, new Point(479, 491));
    polygon.setPoint(2, new Point(479, 521));
    polygon.setPoint(3, new Point(449, 521));
    new ShapeRef(router, polygon, 1);
    polygon = new Polygon(4);
    polygon.setPoint(0, new Point(449, 583));
    polygon.setPoint(1, new Point(479, 583));
    polygon.setPoint(2, new Point(479, 613));
    polygon.setPoint(3, new Point(449, 613));
    new ShapeRef(router, polygon, 1);
    polygon = new Polygon(4);
    polygon.setPoint(0, new Point(354, 583));
    polygon.setPoint(1, new Point(384, 583));
    polygon.setPoint(2, new Point(384, 613));
    polygon.setPoint(3, new Point(354, 613));
    new ShapeRef(router, polygon, 2);
    polygon = new Polygon(4);
    polygon.setPoint(0, new Point(354, 354));
    polygon.setPoint(1, new Point(384, 354));
    polygon.setPoint(2, new Point(384, 384));
    polygon.setPoint(3, new Point(354, 384));
    new ShapeRef(router, polygon, 3);
    polygon = new Polygon(4);
    polygon.setPoint(0, new Point(252.5, 354));
    polygon.setPoint(1, new Point(282.5, 354));
    polygon.setPoint(2, new Point(282.5, 384));
    polygon.setPoint(3, new Point(252.5, 384));
    new ShapeRef(router, polygon, 4);
    polygon = new Polygon(4);
    polygon.setPoint(0, new Point(252.5, 583));
    polygon.setPoint(1, new Point(282.5, 583));
    polygon.setPoint(2, new Point(282.5, 613));
    polygon.setPoint(3, new Point(252.5, 613));
    new ShapeRef(router, polygon, 5);
    polygon = new Polygon(4);
    polygon.setPoint(0, new Point(151, 583));
    polygon.setPoint(1, new Point(181, 583));
    polygon.setPoint(2, new Point(181, 613));
    polygon.setPoint(3, new Point(151, 613));
    new ShapeRef(router, polygon, 6);
    polygon = new Polygon(4);
    polygon.setPoint(0, new Point(151, 130));
    polygon.setPoint(1, new Point(181, 130));
    polygon.setPoint(2, new Point(181, 160));
    polygon.setPoint(3, new Point(151, 160));
    new ShapeRef(router, polygon, 7);
    polygon = new Polygon(4);
    polygon.setPoint(0, new Point(520, 491));
    polygon.setPoint(1, new Point(550, 491));
    polygon.setPoint(2, new Point(550, 521));
    polygon.setPoint(3, new Point(520, 521));
    new ShapeRef(router, polygon, 8);
    polygon = new Polygon(4);
    polygon.setPoint(0, new Point(520, 354));
    polygon.setPoint(1, new Point(550, 354));
    polygon.setPoint(2, new Point(550, 384));
    polygon.setPoint(3, new Point(520, 384));
    new ShapeRef(router, polygon, 9);
    polygon = new Polygon(4);
    polygon.setPoint(0, new Point(633, 354));
    polygon.setPoint(1, new Point(663, 354));
    polygon.setPoint(2, new Point(663, 384));
    polygon.setPoint(3, new Point(633, 384));
    new ShapeRef(router, polygon, 10);
    polygon = new Polygon(4);
    polygon.setPoint(0, new Point(633, 583));
    polygon.setPoint(1, new Point(663, 583));
    polygon.setPoint(2, new Point(663, 613));
    polygon.setPoint(3, new Point(633, 613));
    new ShapeRef(router, polygon, 11);
    polygon = new Polygon(4);
    polygon.setPoint(0, new Point(741, 583));
    polygon.setPoint(1, new Point(771, 583));
    polygon.setPoint(2, new Point(771, 613));
    polygon.setPoint(3, new Point(741, 613));
    new ShapeRef(router, polygon, 12);
    polygon = new Polygon(4);
    polygon.setPoint(0, new Point(741, 130));
    polygon.setPoint(1, new Point(771, 130));
    polygon.setPoint(2, new Point(771, 160));
    polygon.setPoint(3, new Point(741, 160));
    new ShapeRef(router, polygon, 13);
    polygon = new Polygon(4);
    polygon.setPoint(0, new Point(459.495, 481.99));
    polygon.setPoint(1, new Point(468.505, 481.99));
    polygon.setPoint(2, new Point(468.505, 491));
    polygon.setPoint(3, new Point(459.495, 491));
    new ShapeRef(router, polygon, 14);
    polygon = new Polygon(4);
    polygon.setPoint(0, new Point(212.495, 481.99));
    polygon.setPoint(1, new Point(221.505, 481.99));
    polygon.setPoint(2, new Point(221.505, 491));
    polygon.setPoint(3, new Point(212.495, 491));
    new ShapeRef(router, polygon, 15);
    polygon = new Polygon(4);
    polygon.setPoint(0, new Point(701.99, 481.99));
    polygon.setPoint(1, new Point(711, 481.99));
    polygon.setPoint(2, new Point(711, 491));
    polygon.setPoint(3, new Point(701.99, 491));
    new ShapeRef(router, polygon, 16);
    connRef = new ConnRef(router, 17);
    srcPt = new ConnEnd(new Point(464, 598), 15);
    connRef.setSourceEndpoint(srcPt);
    dstPt = new ConnEnd(new Point(369, 598), 15);
    connRef.setDestEndpoint(dstPt);
    connRef.setRoutingType(ConnType.Orthogonal);
    newRoute._id = 17;
    resizePolygon(newRoute, 2);
    newRoute.setPoint(0, new Point(464, 598));
    newRoute.setPoint(1, new Point(369, 598));
    connRef.setFixedRoute(newRoute);
    connRef = new ConnRef(router, 18);
    srcPt = new ConnEnd(new Point(267.5, 598), 15);
    connRef.setSourceEndpoint(srcPt);
    dstPt = new ConnEnd(new Point(166, 598), 15);
    connRef.setDestEndpoint(dstPt);
    connRef.setRoutingType(ConnType.Orthogonal);
    newRoute._id = 18;
    resizePolygon(newRoute, 2);
    newRoute.setPoint(0, new Point(267.5, 598));
    newRoute.setPoint(1, new Point(166, 598));
    connRef.setFixedRoute(newRoute);
    connRef = new ConnRef(router, 19);
    srcPt = new ConnEnd(new Point(369, 598), 15);
    connRef.setSourceEndpoint(srcPt);
    dstPt = new ConnEnd(new Point(369, 369), 15);
    connRef.setDestEndpoint(dstPt);
    connRef.setRoutingType(ConnType.Orthogonal);
    newRoute._id = 19;
    resizePolygon(newRoute, 2);
    newRoute.setPoint(0, new Point(369, 598));
    newRoute.setPoint(1, new Point(369, 369));
    connRef.setFixedRoute(newRoute);
    connRef = new ConnRef(router, 20);
    srcPt = new ConnEnd(new Point(464, 506), 15);
    connRef.setSourceEndpoint(srcPt);
    dstPt = new ConnEnd(new Point(464, 598), 15);
    connRef.setDestEndpoint(dstPt);
    connRef.setRoutingType(ConnType.Orthogonal);
    newRoute._id = 20;
    resizePolygon(newRoute, 2);
    newRoute.setPoint(0, new Point(464, 506));
    newRoute.setPoint(1, new Point(464, 598));
    connRef.setFixedRoute(newRoute);
    connRef = new ConnRef(router, 21);
    srcPt = new ConnEnd(new Point(756, 598), 15);
    connRef.setSourceEndpoint(srcPt);
    dstPt = new ConnEnd(new Point(756, 145), 15);
    connRef.setDestEndpoint(dstPt);
    connRef.setRoutingType(ConnType.Orthogonal);
    newRoute._id = 21;
    resizePolygon(newRoute, 2);
    newRoute.setPoint(0, new Point(756, 598));
    newRoute.setPoint(1, new Point(756, 145));
    connRef.setFixedRoute(newRoute);
    connRef = new ConnRef(router, 22);
    srcPt = new ConnEnd(new Point(369, 369), 15);
    connRef.setSourceEndpoint(srcPt);
    dstPt = new ConnEnd(new Point(267.5, 369), 15);
    connRef.setDestEndpoint(dstPt);
    connRef.setRoutingType(ConnType.Orthogonal);
    newRoute._id = 22;
    resizePolygon(newRoute, 2);
    newRoute.setPoint(0, new Point(369, 369));
    newRoute.setPoint(1, new Point(267.5, 369));
    connRef.setFixedRoute(newRoute);
    connRef = new ConnRef(router, 23);
    srcPt = new ConnEnd(new Point(166, 145), 15);
    connRef.setSourceEndpoint(srcPt);
    dstPt = new ConnEnd(new Point(756, 145), 15);
    connRef.setDestEndpoint(dstPt);
    connRef.setRoutingType(ConnType.Orthogonal);
    newRoute._id = 23;
    resizePolygon(newRoute, 2);
    newRoute.setPoint(0, new Point(166, 145));
    newRoute.setPoint(1, new Point(756, 145));
    connRef.setFixedRoute(newRoute);
    connRef = new ConnRef(router, 24);
    srcPt = new ConnEnd(new Point(464, 486.495), 15);
    connRef.setSourceEndpoint(srcPt);
    dstPt = new ConnEnd(new Point(706.495, 486.495), 15);
    connRef.setDestEndpoint(dstPt);
    connRef.setRoutingType(ConnType.Orthogonal);
    connRef = new ConnRef(router, 25);
    srcPt = new ConnEnd(new Point(535, 369), 15);
    connRef.setSourceEndpoint(srcPt);
    dstPt = new ConnEnd(new Point(535, 506), 15);
    connRef.setDestEndpoint(dstPt);
    connRef.setRoutingType(ConnType.Orthogonal);
    newRoute._id = 25;
    resizePolygon(newRoute, 2);
    newRoute.setPoint(0, new Point(535, 369));
    newRoute.setPoint(1, new Point(535, 506));
    connRef.setFixedRoute(newRoute);
    connRef = new ConnRef(router, 26);
    srcPt = new ConnEnd(new Point(648, 598), 15);
    connRef.setSourceEndpoint(srcPt);
    dstPt = new ConnEnd(new Point(648, 369), 15);
    connRef.setDestEndpoint(dstPt);
    connRef.setRoutingType(ConnType.Orthogonal);
    newRoute._id = 26;
    resizePolygon(newRoute, 2);
    newRoute.setPoint(0, new Point(648, 598));
    newRoute.setPoint(1, new Point(648, 369));
    connRef.setFixedRoute(newRoute);
    connRef = new ConnRef(router, 27);
    srcPt = new ConnEnd(new Point(464, 486.495), 15);
    connRef.setSourceEndpoint(srcPt);
    dstPt = new ConnEnd(new Point(217, 486.495), 15);
    connRef.setDestEndpoint(dstPt);
    connRef.setRoutingType(ConnType.Orthogonal);
    connRef = new ConnRef(router, 28);
    srcPt = new ConnEnd(new Point(648, 598), 15);
    connRef.setSourceEndpoint(srcPt);
    dstPt = new ConnEnd(new Point(756, 598), 15);
    connRef.setDestEndpoint(dstPt);
    connRef.setRoutingType(ConnType.Orthogonal);
    newRoute._id = 28;
    resizePolygon(newRoute, 2);
    newRoute.setPoint(0, new Point(648, 598));
    newRoute.setPoint(1, new Point(756, 598));
    connRef.setFixedRoute(newRoute);
    connRef = new ConnRef(router, 29);
    srcPt = new ConnEnd(new Point(166, 598), 15);
    connRef.setSourceEndpoint(srcPt);
    dstPt = new ConnEnd(new Point(166, 145), 15);
    connRef.setDestEndpoint(dstPt);
    connRef.setRoutingType(ConnType.Orthogonal);
    newRoute._id = 29;
    resizePolygon(newRoute, 2);
    newRoute.setPoint(0, new Point(166, 598));
    newRoute.setPoint(1, new Point(166, 145));
    connRef.setFixedRoute(newRoute);
    connRef = new ConnRef(router, 30);
    srcPt = new ConnEnd(new Point(648, 369), 15);
    connRef.setSourceEndpoint(srcPt);
    dstPt = new ConnEnd(new Point(535, 369), 15);
    connRef.setDestEndpoint(dstPt);
    connRef.setRoutingType(ConnType.Orthogonal);
    newRoute._id = 30;
    resizePolygon(newRoute, 2);
    newRoute.setPoint(0, new Point(648, 369));
    newRoute.setPoint(1, new Point(535, 369));
    connRef.setFixedRoute(newRoute);
    connRef = new ConnRef(router, 31);
    srcPt = new ConnEnd(new Point(267.5, 369), 15);
    connRef.setSourceEndpoint(srcPt);
    dstPt = new ConnEnd(new Point(267.5, 598), 15);
    connRef.setDestEndpoint(dstPt);
    connRef.setRoutingType(ConnType.Orthogonal);
    newRoute._id = 31;
    resizePolygon(newRoute, 2);
    newRoute.setPoint(0, new Point(267.5, 369));
    newRoute.setPoint(1, new Point(267.5, 598));
    connRef.setFixedRoute(newRoute);
    connRef = new ConnRef(router, 32);
    srcPt = new ConnEnd(new Point(535, 506), 15);
    connRef.setSourceEndpoint(srcPt);
    dstPt = new ConnEnd(new Point(464, 506), 15);
    connRef.setDestEndpoint(dstPt);
    connRef.setRoutingType(ConnType.Orthogonal);
    newRoute._id = 32;
    resizePolygon(newRoute, 2);
    newRoute.setPoint(0, new Point(535, 506));
    newRoute.setPoint(1, new Point(464, 506));
    connRef.setFixedRoute(newRoute);
    router.processTransaction();
    int crossings = router.existsCrossings();
    assertFalse(crossings > 0);
    }

    private static void resizePolygon(Polygon polygon, int size)
    {
        polygon.ps.clear();
        while (polygon.ps.size() < size) {
            polygon.ps.add(new Point());
        }
    }
}
